services:
  dockeraspnetmysqldio:
    image: ${DOCKER_REGISTRY-}dockeraspnetmysqldio
    build:
      context: .
      dockerfile: DockerAspnetMysqlDio/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=dockerdbdio;User ID=root;Password=password;
    depends_on:
      - db

  db:
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockerdbdio
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

volumes:
  db_data: # Define a named volume for MySQL data persistence
